name: planets
description: App planets.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

vars:
  clean: flutter clean
  get: flutter pub get
  runner: flutter pub run build_runner
scripts:
  mobx_build: $runner build
  mobx_watch: $clean & $get & $runner watch
  mobx_build_clean: $clean & $get & $runner build --delete-conflicting-outputs

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:

  supercharged: ^1.10.0
  simple_animations: ^2.2.2

  dio: ^3.0.10
  flutter_mobx: ^1.1.0+2
  mobx: ^1.2.1+2
  flutter_modular: ^2.0.0+1
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_launcher_icons: "^0.8.0"
  #  mockito: ^4.1.2
  modular_codegen: ^2.0.0+1
  mobx_codegen: ^1.1.0+2
  build_runner: ^1.10.1
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icon/icon.png"


flutter:
  uses-material-design: true
  assets:
    - assets/images/planets/
    - assets/3d/
